/* This file was generated by SableCC (http://www.sablecc.org/). */

package mini.node;

import java.util.*;
import mini.analysis.*;

@SuppressWarnings("nls")
public final class AElseList extends PList
{
    private final LinkedList<PStmt> _elseStmts_ = new LinkedList<PStmt>();

    public AElseList()
    {
        // Constructor
    }

    public AElseList(
        @SuppressWarnings("hiding") List<?> _elseStmts_)
    {
        // Constructor
        setElseStmts(_elseStmts_);

    }

    @Override
    public Object clone()
    {
        return new AElseList(
            cloneList(this._elseStmts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseList(this);
    }

    public LinkedList<PStmt> getElseStmts()
    {
        return this._elseStmts_;
    }

    public void setElseStmts(List<?> list)
    {
        for(PStmt e : this._elseStmts_)
        {
            e.parent(null);
        }
        this._elseStmts_.clear();

        for(Object obj_e : list)
        {
            PStmt e = (PStmt) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._elseStmts_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._elseStmts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._elseStmts_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStmt> i = this._elseStmts_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
